# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c6af7ffd1e34df3896133e61d2a061dd5a0f1bc4ecc5ccb3d805bcbe79f39b30f46d3d30de3aecc335c433b238e0802becc32a15aa05f44034b0073affebd779

test:
  secret_key_base: e12de6ba8851edc8cd9ec900e1c9df7fe00dc37855a322df678b04b558fb57c0db393d7de634ca7f85e685d1aac38ed56ea2806567929a6bc5e029b3bbedd9a9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
